PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ps: <http://www.wikidata.org/prop/statement/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?journal ?journal_title WHERE {
  [ p:P235 []; ]
    (p:P703/prov:wasDerivedFrom/pr:P248/wdt:P1433) ?journal.
  ?journal wdt:P1476 ?journal_title.
}
# LIMIT 2500