PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wikibase: <http://wikiba.se/ontology#>

SELECT ?rank ?rankLabel WHERE {
    ?rank wdt:P31 wd:Q427626.
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
LIMIT 200
