PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_pdb_ligand WHERE {
    ?structure wdt:P3636 ?structure_id_pdb_ligand. hint:Prior hint:rangeSafe TRUE. # int
}
# LIMIT 2000000
