PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_chebi WHERE {
    ?structure wdt:P683 ?structure_id_chebi. hint:Prior hint:rangeSafe TRUE. # int
}
# LIMIT 2000000
