PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_cas WHERE {
    ?structure wdt:P231 ?structure_id_cas. hint:Prior hint:rangeSafe TRUE. # str
}
# LIMIT 2000000
