PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_pdb_structure WHERE {
    ?structure wdt:P638 ?structure_id_pdb_structure. hint:Prior hint:rangeSafe true. # int
}
# LIMIT 2000000
