PREFIX p: <http://www.wikidata.org/prop/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?stereoisomer WHERE {
    ?structure wdt:P3364 ?stereoisomer.
    ?structure p:P703 [].
}
# LIMIT 500000
