PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_unichem WHERE {
    ?structure wdt:P11089 ?structure_id_unichem. hint:Prior hint:rangeSafe TRUE. # int
}
