PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_npatlas WHERE {
    ?structure wdt:P7746 ?structure_id_npatlas. hint:Prior hint:rangeSafe TRUE. # str
}
