PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_knapsack WHERE {
    ?structure wdt:P2064 ?structure_id_knapsack. hint:Prior hint:rangeSafe TRUE. # str
}
