PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?structure ?structure_id_surechembl WHERE {
    ?structure wdt:P2877 ?structure_id_surechembl. hint:Prior hint:rangeSafe TRUE. # str
}
