PREFIX hint: <http://www.bigdata.com/queryHints#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?taxon ?taxon_id_col WHERE {
    ?taxon wdt:P10585 ?taxon_id_col. hint:Prior hint:rangeSafe TRUE. # str
}
# LIMIT 2500000
