PREFIX wdt: <http://www.wikidata.org/prop/direct/>
SELECT ?taxon ?relative ?distance WITH {
  SELECT DISTINCT ?taxon WHERE {
    [] wdt:P703 ?subtax.
    ?subtax wdt:P171 ?taxon.
  }
} AS %taxa WHERE {
  SELECT DISTINCT ?taxon ?relative (COUNT(DISTINCT ?rel) AS ?distance) WHERE  {
  INCLUDE %taxa
  ?taxon wdt:P171* ?rel.
  ?rel wdt:P171+ ?relative.
  } GROUP BY ?taxon ?relative
}
