PREFIX p: <http://www.wikidata.org/prop/>
PREFIX pr: <http://www.wikidata.org/prop/reference/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX ps: <http://www.wikidata.org/prop/statement/>

SELECT ?structure ?taxon ?reference WHERE {
  ?structure p:P235 [];
    p:P703 [
      ps:P703 ?taxon;
              (prov:wasDerivedFrom/pr:P248) ?reference;
    ]
}
