FROM python:3.14.1-slim
RUN apt-get update && apt-get install -y --no-install-recommends \
    libxi6 \
    libxrender1 \
    libxtst6 \
    && rm -rf /var/lib/apt/lists/*
RUN pip install uv
COPY uv.lock pyproject.toml README.md ./
RUN --mount=type=cache,target=/root/.cache/pdm uv sync
RUN mkdir /app /app/data
RUN adduser nonroot
RUN chown -R nonroot /app/data
USER nonroot
WORKDIR /app
CMD [ "uvicorn", "api.api:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]
