FROM docker.io/library/python:3.12-slim
RUN apt update && apt install -y libxrender1 libxtst6 libxi6
RUN pip install uv
COPY uv.lock pyproject.toml ./
RUN uv sync
RUN mkdir /app /app/data
RUN adduser nonroot
RUN chown -R nonroot /app/data
USER nonroot
WORKDIR /app
CMD [ "uvicorn", "api.api:app", "--reload", "--host", "0.0.0.0", "--port", "5000"]
