# A docker-compose file for a two services system. One is the backend, with the Dockerfile in this directory
# the other one is inside frontend.

version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - backend_data:/app/data
  frontend:
    build: frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  indigo:
    image: epmlsop/indigo-service:latest
    ports:
      - "8002:80"
    restart: always

volumes:
    backend_data:
