openapi: 3.1.0
info:
  title: LOTUS API Specification
  description: LOTUS API Specification
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://search.nprod.net/api'

paths:
  /taxas:
    $ref: './paths/taxa/search.yaml'
  /taxas/{wid}:
    $ref: './paths/taxa/get.yaml'
  /structures:
    $ref: './paths/structures/search.yaml'
  /structures/{wid}:
    $ref: './paths/structures/get.yaml'
components:
  schemas:
    taxa:
        $ref: "./schemas/taxon.yaml"
    structure:
        $ref: "./schemas/structure.yaml"
