---
openapi: 3.1.0
info:
  title: LOTUS FastAPI
  description: |

    LOTUSFast API helps you do awesome stuff. 🚀
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: "1.0"
servers:
  - url: https://search.nprod.net/v1_0
paths:
  /references:
    $ref: ./paths/references/post.yaml
  /structures:
    $ref: ./paths/structures/post.yaml
  /taxa:
    $ref: ./paths/taxa/post.yaml
  /triplets:
    $ref: ./paths/triplets/post.yaml
  /autocomplete/taxa:
    $ref: ./paths/autocomplete/taxa/post.yaml
  /depiction/structure:
    $ref: ./paths/depiction/structure.yaml
  /descriptors:
    $ref: ./paths/descriptors/get.yaml
components:
  schemas:
    Item:
      $ref: ./schemas/item.yaml
    # ReferenceInfo:
    #   $ref: ./schemas/referenceInfo.yaml
    ReferenceResult:
      $ref: ./schemas/referenceResult.yaml
    # StructureInfo:
    #   $ref: ./schemas/structureInfo.yaml
    StructureResult:
      $ref: ./schemas/structureResult.yaml
    # TaxonInfo:
    #   $ref: ./schemas/taxonInfo.yaml
    TaxonResult:
      $ref: ./schemas/taxonResult.yaml
    TripletResult:
      $ref: ./schemas/tripletResult.yaml
    HTTPValidationError:
      $ref: ./schemas/validationError.yaml
