openapi: 3.1.0
info:
  title: LOTUS API Specification
  description: LOTUS API Specification
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'https://search.nprod.net/api'

paths:
  /couples:
    $ref: './paths/couples/post.yaml'
  /couples/{wid}:
    $ref: './paths/couples/get.yaml'
  /structures:
    $ref: './paths/structures/post.yaml'
  /structures/{wid}:
    $ref: './paths/structures/get.yaml'
  /taxa:
    $ref: './paths/taxa/post.yaml'
  /taxa/{wid}:
    $ref: './paths/taxa/get.yaml'
components:
  schemas:
    couple:
        $ref: "./schemas/couple.yaml"
    structures:
        $ref: "./schemas/structure.yaml"
    taxa:
        $ref: "./schemas/taxon.yaml"
    
