### TODO update

###  Empty query should be fast or fail
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{ }



### Query 1
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "taxon": 
  {
    "wid": 158572
  }
}

### Query 1
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "c1ccccc1"
  }
}



### Query 2
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/structures -d '{"structure":"Cl", "substructure_search": true, "taxon_name": "Gentiana septemfida", "reference_doi": "10.1021/NP50081A018"}'
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/taxa -d '{"structure_wid": 27151406, "taxon_wid": 158572 ,"reference_wid": 44488598}'
POST http://127.0.0.1:5000/v1_0/taxa
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/taxa -d '{"structure":"Cl", "substructure_search": true, "taxon_name": "Gentiana septemfida", "reference_doi": "10.1021/NP50081A018"}'
POST http://127.0.0.1:5000/v1_0/taxa
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/references -d '{"structure_wid": 27151406, "taxon_wid": 158572 ,"reference_wid": 44488598}'
POST http://127.0.0.1:5000/v1_0/references
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/references -d '{"structure":"Cl", "substructure_search": true, "taxon_name": "Gentiana septemfida", "reference_doi": "10.1021/NP50081A018"}'
POST http://127.0.0.1:5000/v1_0/references
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/references -d '{"structure_wid": 27151406, "taxon_wid": 158572 ,"reference_wid": 44488598}'
POST http://127.0.0.1:5000/v1_0/references
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "C",
    "option": 
    {
      "substructure_search": true
    }
  },
  "limit": 0,
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/triplets -d '{"structure_wid": 27151406, "taxon_wid": 158572 ,"reference_wid": 44488598}'
POST http://127.0.0.1:5000/v1_0/triplets
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}

###

# curl -XPOST -H 'Accept: application/json' -H 'Content-Type: application/json' http://127.0.0.1:5000/v1_0/triplets -d '{"structure":"Cl", "substructure_search": true, "taxon_name": "Gentiana septemfida", "reference_doi": "10.1021/NP50081A018"}'
POST http://127.0.0.1:5000/v1_0/triplets
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}
