### Query structures - empty
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{ }


### Query structures - taxon wid
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "taxon": 
  {
    "wid": 158572
  }
}


### Query structures - smiles
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "c1ccccc1"
  }
}


### Query structures - structure wid and taxon wid and reference wid
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}


### Query structures - substructure Cl and taxon Gentiana septemfida and reference 10.1021/NP50081A018
POST http://127.0.0.1:5000/v1_0/structures
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}


### Query taxa - taxon name
POST http://127.0.0.1:5000/v1_0/taxa
Accept: application/json
Content-Type: application/json

{
  "taxon_name": "Ta"
}


### Query taxa - structure wid and taxon wid and reference wid
POST http://127.0.0.1:5000/v1_0/taxa
### Query taxa - structure wid and taxon wid and reference wid
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}


### Query taxa - substructure Cl and taxon Gentiana septemfida and reference 10.1021/NP50081A018
POST http://127.0.0.1:5000/v1_0/taxa
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}


### Query taxa - structure wid and taxon wid and reference wid
POST http://127.0.0.1:5000/v1_0/references
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}


### Query references - substructure Cl and taxon Gentiana septemfida and reference 10.1021/NP50081A018
POST http://127.0.0.1:5000/v1_0/references
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}


### Query triplets - structure wid and taxon wid and reference wid
POST http://127.0.0.1:5000/v1_0/triplets
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "wid": 27151406
  },
  "taxon":
  {
    "wid": 158572
  },
  "reference":
  { 
    "wid": 44488598
  }
}


### Query triplets - substructure Cl and taxon Gentiana septemfida and reference 10.1021/NP50081A018
POST http://127.0.0.1:5000/v1_0/triplets
Accept: application/json
Content-Type: application/json

{
  "structure": 
  {
    "molecule": "Cl",
    "option": 
    {
      "substructure_search": true
    }
  },
  "taxon":
  {
    "name": "Gentiana septemfida"
  },
  "reference":
  { 
    "doi": "10.1021/NP50081A018"
  }
}

### TODO add some others to showcase formula/descriptors/journal search