# Generated by Django 4.2.4 on 2023-08-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reference_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="data",
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ReferenceData",
        ),
    ]
