# Generated by Django 4.2.4 on 2023-08-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_manager', '0003_reference_id_alter_reference_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='wid',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
